### PR TITLE
OverVue 6.0

### PR DESCRIPTION
**Pull request by megatera**
- Refreshed UI
- Ability to export in TypeScript
- Ability to import components
- Ability to export individual components
- Docker containerization
- Note functionality
- Interactive project tree
- Export boilerplate with Vite instead of Webpack
- Get Started tutorial
- Updated dependencies
- Bug fixes

### CODE REVIEW

**Review by jbbake — APPROVED** [review]
Great job team!

**Review by apaparian — APPROVED** [review]
OverVue 6.0's collected iteration features and updates:

**Review by MrBeeAreWhy — APPROVED** [review]
Amazing work, everyone.

**Comment by Kerolos-Nesem** [comment]
Great work team! Everyone exceeded the expectations!

**Pull request merged**
