### PR TITLE
Rob/pinia

### PR DESCRIPTION
**Pull request by robsinz**
## Checklist

- [ ] I've followed the [Contributing guidelines](https://github.com/community-health-demo/.github/blob/main/CONTRIBUTING.md)
- [ ] I've titled my PR according to the [Conventional Commits spec](https://conventionalcommits.org)
- [ ] I've linked an open issue
- [ ] I've added tests that fail without this PR but pass with it
- [ ] I've linted and tested my code
- [ ] I've updated documentation (if appropriate)

### CODE REVIEW

**Review by Kelementz916 — APPROVED** [review]
Awesome work! This will definitely make the app smoother

**Review by DanielGaran02 — APPROVED** [review]
glad we got compisition API functionality

**Review by anthonyHerr — APPROVED** [review]
Great work on the toggle functionality between options and composition API!

**Review by RoderickXii — APPROVED** [review]
nice job team getting the code snippet to show pinia code

**Pull request merged**
