### PR TITLE
Ah/final touches

### PR DESCRIPTION
**Pull request by anthonyHerr**
## Checklist

- [ ] I've followed the [Contributing guidelines](https://github.com/community-health-demo/.github/blob/main/CONTRIBUTING.md)
- [ ] I've titled my PR according to the [Conventional Commits spec](https://conventionalcommits.org)
- [ ] I've linked an open issue
- [ ] I've added tests that fail without this PR but pass with it
- [ ] I've linted and tested my code
- [ ] I've updated documentation (if appropriate)

### CODE REVIEW

**Review by robsinz — APPROVED** [review]
impressive!

**Review by Kelementz916 — APPROVED** [review]
These changes are great! Awesome UI/UX changes

**Review by RoderickXii — APPROVED** [review]
Nice work Anthony!

**Review by DanielGaran02 — APPROVED** [review]
looks great good job!

**Comment by julesdmai** [comment]
Well done everyone!

**Pull request merged**
